# Generated by Django 5.2.4 on 2026-06-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_tableorder_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Phân cách bằng dấu phẩy. VD: nướng,hấp,hải sản,bò",
                max_length=300,
                verbose_name="Tags",
            ),
        ),
    ]
